version: '3.9'

services:
  postgres-stoom:
    container_name: postgres-stoom
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: store
      PGDATA: /data/postgres
    ports:
      - "5432:5432"